({
	getData: function() {
		var hData = {
			   "rootNode":{
			   				"id":"0MI1a0000004d82GAA"
			   			  },
			   "nodes":[
			      {
			         "type":"text",
			         "text":"Barnstable",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004dCZGAY",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004dwOGAQ",
			         "description":"Barnstable County",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"Berkshire",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004dCZGAY",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004dwTGAQ",
			         "description":"Berkshire County",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"New England",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d82GAA",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d8CGAQ",
			         "description":"New England States",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"Bristol",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004dCZGAY",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004dwYGAQ",
			         "description":"Bristol County",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"Central",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d7dGAA",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d7sGAA",
			         "description":"Central States",
			         "data":null
			      },
			      {
			         "type":"image",
			         "text":"CT",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d8CGAQ",
			         "leftIconClick":null,
			         "imageURL":"http://i.kinja-img.com/gawker-media/image/upload/s--RWUij5kb--/c_fit,fl_progressive,q_80,w_636/766401252534717839.png",
			         "id":"0MI1a0000004dCjGAI",
			         "description":"Connecticut",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"Delaware Valley",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d82GAA",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d8MGAQ",
			         "description":"PA & DE",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"Dukes",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004dCZGAY",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004dwdGAA",
			         "description":"Dukes County",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"East",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d7dGAA",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d7nGAA",
			         "description":"US Eastern States",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"Essex",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004dCZGAY",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004dwiGAA",
			         "description":"Essex County",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"Franklin",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004dCZGAY",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004dwnGAA",
			         "description":"Franklin County",
			         "data":null
			      },
			      {
			         "type":"image",
			         "text":"ME",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d8CGAQ",
			         "leftIconClick":null,
			         "imageURL":"http://i.kinja-img.com/gawker-media/image/upload/s--pr98VYAd--/c_fit,fl_progressive,q_80,w_636/766401263384603535.png",
			         "id":"0MI1a0000004dCtGAI",
			         "description":"Maine",
			         "data":null
			      },
			      {
			         "type":"image",
			         "text":"MA",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d8CGAQ",
			         "leftIconClick":null,
			         "imageURL":"http://i.kinja-img.com/gawker-media/image/upload/s--TBbZbbVv--/c_fit,fl_progressive,q_80,w_636/nxsvfycao6bfi0erutnm.png",
			         "id":"0MI1a0000004dCZGAY",
			         "description":"Massachusetts",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"New York",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d82GAA",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d8HGAQ",
			         "description":"Upstate and NYC",
			         "data":null
			      },
			      {
			         "type":"image",
			         "text":"NH",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d8CGAQ",
			         "leftIconClick":null,
			         "imageURL":"http://i.kinja-img.com/gawker-media/image/upload/s--1UMUq-cR--/c_fit,fl_progressive,q_80,w_636/ulldjhmcl8e6lhcoovqu.png",
			         "id":"0MI1a0000004dCoGAI",
			         "description":"New Hampshire",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"North East",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d7nGAA",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d82GAA",
			         "description":"North Eastern States",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"South East",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d7nGAA",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d87GAA",
			         "description":"South Eastern states",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"US",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":null,
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d7dGAA",
			         "description":"United States",
			         "data":null
			      },
			      {
			         "type":"image",
			         "text":"VT",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d8CGAQ",
			         "leftIconClick":null,
			         "imageURL":"http://i.kinja-img.com/gawker-media/image/upload/s--iq465hdV--/c_fit,fl_progressive,q_80,w_636/766437548520254638.png",
			         "id":"0MI1a0000004dCeGAI",
			         "description":"Vermont",
			         "data":null
			      },
			      {
			         "type":"text",
			         "text":"West",
			         "rootNodeClick":{
			            "params":"{\"scope\":\"Account\"}",
			            "name":"e.force:navigateToObjectHome"
			         },
			         "rightIconClick":null,
			         "parentid":"0MI1a0000004d7dGAA",
			         "leftIconClick":null,
			         "imageURL":null,
			         "id":"0MI1a0000004d7xGAA",
			         "description":"Western States",
			         "data":null
			      }
			   ]
		}
		return hData;	
	}

})